### ISSUE TITLE
arrow keys thru search results?

### ISSUE THREAD

**Issue by shoesandsocks** [chingu-voyage3/fair-rentals#39]
would have to put some kind of keydown/keyup watcher, on those divs? or is there a `tabfocus`-type HTML/CSS trick that would make arrows work? `Tab` and `Return` "just work" but the arrow keys need some love...

**Comment by Sjbrimley26** [comment]
The keyup/keydown way is the only way I know

**Comment by shoesandsocks** [comment]
https://github.com/kenny-hibino/react-places-autocomplete 

This package looks like the really comprehensive way to deal with the issue; a little overwhelming at the moment.

**Comment by shoesandsocks** [comment]
I'm closing this in lieu of #54. I hope an eventual re-design includes this feature or operates in some  other fashion entirely. (_e.g._ picking a spot on a map instead of a text list)
