### ISSUE TITLE
sort reviews (oldest/newest, worst/best)

### ISSUE THREAD

**Issue by shoesandsocks** [chingu-voyage3/fair-rentals#43]
not ready to tackle this yet, but noting here.

**Comment by shoesandsocks** [comment]
...and if they're sorted by time, should our EditReview mutation change the datestamp? or add another datestamp `editedAt` or something? (if so, presentation of reviews needs to be tweaked to show...)

**Comment by Sjbrimley26** [comment]
The editreview mutation already updates a property called 'last_edited' on the review document to the current Date. I tested this on reviews that didn't already have the property and it adds it so we should be good to go on that part.

**Comment by Sjbrimley26** [comment]
Oh I don't know if you know this but I actually added a line to your `latest_reviews` function so they are sorted by post date, that's why it's been showing up the most recents on the splash page.

**Comment by Sjbrimley26** [comment]
Gonna leave this open because the queries are pretty inefficient and the reviews render strangely when they are sorted.

**Comment by shoesandsocks** [comment]
that sort rendering's probably weird because of my simplified animation thing. i'll take a look

**Comment by shoesandsocks** [comment]
another sort bug, I think: I changed the stars on a Brandenburg Gate review, the one that reads "updated sunday 4:07." It now has five stars, but when I sort by Worst, it's at the top when it should be at the bottom... right?

**Comment by Sjbrimley26** [comment]
Are you on `43-improvements` ? I'm not getting that particular error

**Comment by shoesandsocks** [comment]
d'oh, sure enough. I just pulled all the `dev-branch` updates but didn't switch to 43-imp to test. Yep, it works.
