### ISSUE TITLE
pagination, eventually

### ISSUE THREAD

**Issue by shoesandsocks** [chingu-voyage3/fair-rentals#53]
as database fills with data, we'll eventually need to paginate results on the Location and Profile pages. (Possibly something that can be pushed down to the Reviews component and handled there.)

**Comment by Sjbrimley26** [comment]
I think I can do this one actually, as long as I can render a good looking-button
https://scalegrid.io/blog/fast-paging-with-mongodb/

**Comment by Sjbrimley26** [comment]
Got it.
