### ISSUE TITLE
Add appropriate page titles

### ISSUE THREAD

**Issue by nikw92** [chingu-voyage3/fair-rentals#56]
Currently the tab just shows 'React App' and doesn't change with respect to where the user is in the app. I think this could be handled with [react-helmet](https://github.com/nfl/react-helmet).

**Comment by shoesandsocks** [comment]
I've seen react helmet used in a tutorial; was pretty cool. the quick-fix for this would be to jump into `client/public/index.html` and just hard-code the change on line 25!

**Comment by nikw92** [comment]
The reason I recommended react-helmet was you could place something like the code below into every container where the page title change is needed. Would hard-coding also take care of that?

```
<helmet>
<title> Appropriate Page Title </title>
</helmet>
```
